### ISSUE TITLE
Credits/Copyright

### ISSUE THREAD

**Issue by talyssonoc** [joshuaalpuerto/node-ddd-boilerplate#16]
Hello, I see that you created this project based on my [Node API boilerplate](https://github.com/talyssonoc/node-api-boilerplate), which is release under MIT license https://github.com/talyssonoc/node-api-boilerplate/blob/master/package.json#L27. Do you mind adding the copyright for my work at the LICENSE file? Thanks.

**Comment by joshuaalpuerto** [comment]
@talyssonoc Absolutely! This boilerplate is actually inspired by your [Node API boilerplate](https://github.com/talyssonoc/node-api-boilerplate).
