### ISSUE TITLE
Whitelisting routes

### ISSUE THREAD

**Issue by BilalHasanKhan** [joshuaalpuerto/node-ddd-boilerplate#31]
Please pardon my ignorance but what's the best way in this to whitelist the routes which do not need authentication like say /register

**Comment by joshuaalpuerto** [comment]
Hey @BilalHasanKhan 

I assume you put the `/register` route under [user module](https://github.com/joshuaalpuerto/node-ddd-boilerplate/blob/master/src/interfaces/http/modules/user/index.js).

You can follow this step

```js
// comment the module level authentication
// router.use(auth.authenticate()) 

  router
    .get('/', auth.authenticate(), (req, res) => {
  ...

  router
    .get('/register', (req, res) => {
 ....
```

This way you can apply authentication per `endpoint`.

**Comment by BilalHasanKhan** [comment]
Many thanks for clarifying.
