### ISSUE TITLE
Acces swagger-ui

### ISSUE THREAD

**Issue by mabihan** [joshuaalpuerto/node-ddd-boilerplate#38]
What's the swagger-ui's URL ? I can only access the json at `http://localhost:4000/api/0.1/swagger.json` for example.

Thank you

**Comment by joshuaalpuerto** [comment]
Hey @JeanReneRobin 

You can access the `swagger-ui` URL at **http://localhost:4000/docs/**

Cheers!

**Comment by mabihan** [comment]
Great, thanks.
