### ISSUE TITLE
Nested Models Query

### ISSUE THREAD

**Issue by BilalHasanKhan** [joshuaalpuerto/node-ddd-boilerplate#39]
How would you recommend nested models be queried from app get.js classes?

**Comment by joshuaalpuerto** [comment]
Hey @BilalHasanKhan,

Sorry not sure about your question. But if this is related about how are you going to `query` association similar to this.

```js
User.findAll({
  include: [{
    model: Project,
    through: {
      attributes: ['createdAt', 'startedAt', 'finishedAt'],
      where: {completed: true}
    }
  }]
});
```

You won't do it on app level. Instead you will inject the `model` as a dependency of the parent repository. 

In this case we have `User` as the parent so under your `/infra/repositories/index.js`

```js
module.exports = ({ database }) => {
  const userModel = database.models.users
  const projectModel = database.models.projects

  return {
    userRepository: User({ model: userModel, projectModel }),
    ....
  }
}
```

This way the `app` don't need to know whatever association your `repository` have, you just use it.

Hope this answer your question. 

Cheers!

**Comment by BilalHasanKhan** [comment]
Makes sense , though one thing I found is with sequelize >4 the association should not be defined in classMethods rather outside of classMethods on the object definition like discussed in this stack;

https://stackoverflow.com/questions/48194490/how-to-upgrade-association-methods-from-sequelize-3-x-to-4-x

**Comment by joshuaalpuerto** [comment]
Yup thats true.. It's actually mentioned on the [readme](https://github.com/joshuaalpuerto/node-ddd-boilerplate#setting-up-associationsmigration-and-model-files).

**Comment by BilalHasanKhan** [comment]
Ahh I completely missed that sorry.
