### ISSUE TITLE
Unable to access http://localhost:5000/api/v1/swagger.json giving 404

### ISSUE THREAD

**Issue by akamanocha** [joshuaalpuerto/node-ddd-boilerplate#62]
I am a bit lost. I have changed only the port and version in .env but I am getting the 404 in the same.

And because of that Failed to Load Spec at this:  http://localhost:5000/docs and at Explore.

What could be the issue? Or anybody has seen same thing?

**Comment by joshuaalpuerto** [comment]
Hey @akamanocha thanks for using this boilerplate. To make swagger aware about the changes you did, you need to change [this](https://github.com/joshuaalpuerto/node-ddd-boilerplate/blob/master/public/docs/index.html#L77-L89) as-well. 

It seems it is not documented well, I will update the docs this weekend or feel free to open a PR.  😉

**Comment by akamanocha** [comment]
Cool, I remember I got that working.

I had to add route.
